sudo: required

services:
  - docker

env:
  global:
    - ICINGAWEB_VERSION=${ICINGAWEB_VERSION:-2.6.2}
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_TYPE=${ICINGAWEB_VERSION:-stable}
    - ICINGAWEB_DIRECTOR=${ICINGAWEB_DIRECTOR:-false}

jobs:
  include:
    - stage: build
      script:
        - make build

    - stage: build and test
      script:
        - make build
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - docker ps | grep -q icingaweb2
        - docker-compose kill
        - docker-compose down

    - stage: push latest docker image
      if: branch = master
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag ${USER}/icingaweb2:latest ${DOCKER_USERNAME}/docker-icingaweb2:latest
        - docker push ${DOCKER_USERNAME}/docker-icingaweb2:latest
        - docker logout

    - stage: push version docker image
      if: branch = master
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag ${USER}/icingaweb2:latest ${DOCKER_USERNAME}/docker-icingaweb2:${ICINGAWEB_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-icingaweb2:${ICINGAWEB_VERSION}
        - docker logout
