# version: '2.0'


database:
  image: bodsch/docker-mysql:1707-30.1
  container_name: database
  hostname: database
  ports:
    - 3306:3306
  environment:
    - MYSQL_SYSTEM_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/docker-data/database:/srv

# the Icinga2 Master
# includes a certificate service to create and provide a icinga certificate
#
icinga2-master:
  image: bodsch/docker-icinga2:1707-30.1
  container_name: icinga2-master
  hostname: icinga2-master.matrix.lan
  ports:
    - 5665:5665
    - 4567:4567
  environment:
    - ICINGA_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
    - MYSQL_HOST=database
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
    - IDO_DATABASE_NAME=icinga2core
    - IDO_PASSWORD=ido.pass
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - ICINGA_CLUSTER=true
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
    - CARBON_HOST=
    - CARBON_PORT=2003
  volumes:
    - /tmp/docker-data/icinga2-master:/srv
  links:
    - database:database

# icingaweb2
#
icingaweb2:
  build: .
  container_name: icingaweb2
  hostname: icingaweb2.matrix.lan
  ports:
    - 80:80
  environment:
    - ICINGA_HOST=icinga2-master.matrix.lan
    - MYSQL_HOST=database
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
    - ICINGA2_CMD_API_USER=root
    - ICINGA2_CMD_API_PASS=icinga
    - ICINGAWEB2_USERS=icinga:icinga,foo:bar
    - IDO_DATABASE_NAME=icinga2core
    - IDO_PASSWORD=ido.pass
  volumes:
    - /tmp/docker-data/icingaweb2:/srv
  links:
    - icinga2-master:icinga2-master.matrix.lan
    - database:database

