#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down nginx"
    /etc/init.d/nginx stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting nginx"

/etc/init.d/nginx start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u www-data www-data > /dev/null; do sleep 5; done
