#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down php5-fpm"
    /etc/init.d/php5-fpm stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting php5-fpm"

/etc/init.d/php5-fpm start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u root,www-data -F /run/php5-fpm.pid > /dev/null
do
  sleep 5s
done

