---
version: '3.3'

services:
  grafana:
    image: bodsch/docker-grafana
    restart: always
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - URL_PATH
      - LOG_LEVEL
      - ROUTER_LOGGING
    volumes:
      - ${PWD}/import/provisioning:/etc/grafana/provisioning:ro
      - ${PWD}/import/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - frontend
      - backend
