---
version: '3.3'

services:
  influxdb:
    restart: always
    image: influxdb:1.7-alpine
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086
    environment:
      - INFLUXDB_DB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
    networks:
      - backend
