---
version: '3.3'

services:
  # the Icinga2 Master
  # includes a certificate service to create and provide a icinga certificate
  icinga2-master:
    image: bodsch/docker-icinga2:latest-master
    container_name: icinga2-master
    hostname: icinga2-master.matrix.lan
    restart: always
    privileged: false
    ports:
      - 5665:5665
      - 8080:8080
    env_file:
      - ${PWD}/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
      - influxdb
    links:
      - database
      - influxdb
    networks:
      - database
      - backend

