#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

docker build \
  --file Dockerfile \
  --rm \
  --compress \
  --build-arg VCS_REF=${GIT_SHA1} \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg BUILD_VERSION=${BUILD_VERSION} \
  --build-arg BUILD_TYPE=${BUILD_TYPE} \
  --build-arg ICINGAWEB_VERSION=${ICINGAWEB_VERSION} \
  --build-arg INSTALL_THEMES=${INSTALL_THEMES} \
  --build-arg INSTALL_MODULES=${INSTALL_MODULES} \
  --tag ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${ICINGAWEB_VERSION} .
