#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

docker rmi \
  -f $(docker images -q ${NS}/${REPO} | uniq)
