#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

echo "BUILD_DATE=${BUILD_DATE}" > .env
echo "BUILD_VERSION=${BUILD_VERSION}" >> .env
echo "BUILD_TYPE=${BUILD_TYPE}" >> .env
echo "ICINGAWEB_VERSION=${ICINGAWEB_VERSION}" >> .env
echo "INSTALL_THEMES=${INSTALL_THEMES}" >> .env
echo "INSTALL_MODULES=${INSTALL_MODULES}" >> .env

docker-compose \
  --file docker-compose_example.yml \
  config > docker-compose.yml
