#!/bin/bash

set -e
set -x

GITHUB_USER=${GITHUB_USER:-bodsch}
WORK_DIR=$(dirname $(readlink --canonicalize "${0}"))
JSON_DIR=$(dirname $(readlink --canonicalize "${0%/*}"))/build
TEMP_DIR=$(mktemp --directory)

pushd ${TEMP_DIR}

echo "current directory: ${PWD}"

default_modules() {

  if [[ -f ${JSON_DIR}/modules.json ]]
  then
    MODULE_JSON=$(cat ${JSON_DIR}/modules.json)
  else
    MODULE_JSON='{
      "Icinga/icingaweb2-module-director": {},
      "Icinga/icingaweb2-module-vsphere": {
        "enable": false
      },
      "Icinga/icingaweb2-module-vspheredb": {},
      "Icinga/icingaweb2-module-graphite": {},
      "Icinga/icingaweb2-module-generictts": {},
      "Icinga/icingaweb2-module-businessprocess": {},
      "Icinga/icingaweb2-module-elasticsearch": {},
      "Icinga/icingaweb2-module-cube": {},
      "Icinga/icingaweb2-module-aws": {},
      "Icinga/icingaweb2-module-fileshipper": {},
      "Icinga/icingaweb2-module-toplevelview": {},
      "Mikesch-mp/icingaweb2-module-grafana.git": {},
      "Mikesch-mp/icingaweb2-module-globe": {},
      "Thomas-Gelf/icingaweb2-module-reporting": {},
      "nbuchwitz/icingaweb2-module-map": {},
      "morgajel/icingaweb2-module-boxydash": {}
    }'
  fi

}

# check github rate limits
# we consume for each REST API call a credit
#
github_ratelimit() {

  local -n VAR=$1

  curl_opts=
  [[ -z ${GITHUB_OAUTH_TOKEN} ]] || curl_opts="--user ${GITHUB_USER}:${GITHUB_OAUTH_TOKEN}"

  remaining=$(curl \
    --silent \
    --include \
    ${curl_opts} \
    https://api.github.com/users/bodsch | grep "X-RateLimit-Remaining: " | awk -F 'X-RateLimit-Remaining: ' '{print $2}')

  echo "RateLimit Remaining: ${remaining}"

  VAR=${remaining}
}


download_modules() {

  echo " - get latest published versions"

  [[ -d cache ]] || mkdir -vp cache

  #current_time=$(date +%s)

  for k in $(echo ${MODULE_JSON} | jq -r '. | to_entries | .[] | .key')
  do
    enable="$(echo "${MODULE_JSON}" | jq -r ".[\"$k\"].enable")"
    use_git="$(echo "${MODULE_JSON}" | jq -r ".[\"$k\"].use_git")"
    [[ "${enable}" == null ]] && enable=true
    [[ "${use_git}" == null ]] && use_git=false

    project="$(echo "${k}" | sed -e 's|\.git||g' -e 's/https\?:\/\///' -e 's|github.com/||g')"
    project_maintainer="$(echo "${project}" | cut -d "/" -f1)"
    project_name="$(echo "${project}" | cut -d "/" -f2 | sed -e 's|icingaweb2-module-||g')"
    outfile=$(echo "${project}" | tr [:upper:] [:lower:] | sed -e 's|/|_|g')

    if [[ -f "cache/github_${outfile}.json" ]]
    then
      file_time=$(stat -c '%Y' "/build/cache/github_${outfile}.json")

      echo "${file_time}"

      if (( file_time < ( current_time - ( 60 * 60 * 24 * 10 ) ) )); then
        echo "cached file for github_${outfile}.json is older than 10 days"
      else
        echo "use cached file"
        cp -v cache/github_${outfile}.json /tmp/
      fi
    else
      echo "no cache"
    fi

    curl_opts=
    [[ -z ${GITHUB_OAUTH_TOKEN} ]] || curl_opts="--user ${GITHUB_USER}:${GITHUB_OAUTH_TOKEN}"

    # download project releated release file from github
    #
    # when ${http_code} == 404 then this module is not released yet!
    #
    if [[ ! -f "cache/github_${outfile}.json" ]]
    then
      code=$(curl \
        ${curl_opts} \
        --silent \
        --header 'Accept: application/vnd.github.v3.full+json' \
        --write-out "%{http_code}\n" \
        --out "cache/github_${outfile}.json" \
        https://api.github.com/repos/${project}/releases/latest)
    fi

    # remove some unneeded parts
    # and add our things
    #
    if [[ -f "cache/github_${outfile}.json" ]] && [[ $(stat -c %s cache/github_${outfile}.json) -gt 0 ]]
    then
      cat "cache/github_${outfile}.json" | \
        jq 'del(.author) | del(.body_html) | del(.body_text) | del(.body) | del(.assets)' | \
        jq ". |= .+ {\"enable\": \"${enable}\", \"use_git\": \"${use_git}\", \"project_maintainer\": \"${project_maintainer}\", \"project_name\": \"${project_name}\" }" > cache/github_${outfile}.json_TMP
      mv cache/github_${outfile}.json_TMP cache/github_${outfile}.json
    fi
  done

  tar -czf cache.tgz cache
}


github_ratelimit remaining

if [[ "${remaining/$'\r'/}" -gt 20 ]]
then
  default_modules
  download_modules

  if [[ -f cache.tgz ]]
  then
    cp -v cache.tgz ${JSON_DIR}/
  fi
else
  echo "sorry, API rate limit fot github exceeded. (only ${remaining} left)"
fi

popd

rm -rfv ${TEMP_DIR}
